FROM demoregistry.dataman-inc.com/library/centos7-base:20160602202509
MAINTAINER ymiao ymiao@dataman-inc.com

#install nginx

ADD nginx.repo /etc/yum.repos.d/
RUN cd /tmp && \
  curl -O http://nginx.org/keys/nginx_signing.key && \
  rpm --import nginx_signing.key && \
  yum update -y && \
  yum install -y nginx

RUN yum clean all && rm -rf /tmp/nginx*

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log
RUN ln -sf /dev/stderr /var/log/nginx/error.log

#demoregistry.dataman-inc.com/library/centos7-nginx1.10.1:v0.1.062700